Marks=[]
f1=int(input("enter a marks name1 "))
Marks.append(f1)
f2=int(input("enter a marks name2 "))
Marks.append(f2)
f3=int(input("enter a marks name3 "))
Marks.append(f3)
f4=int(input("enter a marks name4 "))
Marks.append(f4)
f5=int(input("enter a marks name5 "))
Marks.append(f5)
f6=int(input("enter a marks name6 "))
Marks.append(f6)
f7=int(input("enter a marks name7 "))
Marks.append(f7)
Marks.sort()
print(Marks)