d={}
name=input("enter a name:")
language=input("enter a lang:")
d.update({name: language})
name=input("enter a name:")
language=input("enter a lang:")
d.update({name: language})
name=input("enter a name:")
language=input("enter a lang:")
d.update({name: language})
name=input("enter a name:")
language=input("enter a lang:")
d.update({name: language})
print(d)